### ISSUE TITLE
请问关于obs虚拟摄像头的问题

### ISSUE THREAD

**Issue by GG22G2** [BruceXing24/Auto_aim_CSgo#2]
我也在尝试做这个，我一开始使用dxgi方式截图，一帧大概要4毫秒。今天看到你说的obs，并尝试了一下游戏录屏，软件中统计的平均延迟只有2.5毫秒，非常的块，但是当我使用opencv去捕获虚拟摄像头的时候，却是一片黑。
请问您能分享一下关于从obs获取屏幕内容的方法吗。

**Comment by BruceXing24** [comment]
> 我也在尝试做这个，我一开始使用dxgi方式截图，一帧大概要4毫秒。今天看到你说的obs，并尝试了一下游戏录屏，软件中统计的平均延迟只有2.5毫秒，非常的块，但是当我使用opencv去捕获虚拟摄像头的时候，却是一片黑。 请问您能分享一下关于从obs获取屏幕内容的方法吗。

除了下载obs,你还需要下载obs virtual camera,我给发下链接。https://obsproject.com/forum/resources/obs-virtualcam.539/.
两个下载到一块，然后你的obs工具栏会多出来了一个虚拟摄像头，打开，在用opencv捕获就可以了。

**Comment by GG22G2** [comment]
> 

十分感谢，现在可以捕获到了。
